-- =============================================================================
-- Migration: RLS policies + storage bucket  (custom, journal-tracked)
-- Apply ORDER: AFTER 0000_*.sql (drizzle-kit migrate handles ordering)
--
-- This file is hand-authored (not generated by drizzle-kit) because:
--   1. The profiles → auth.users FK references the Supabase-owned auth schema,
--      which drizzle-kit cannot model without trying to CREATE auth.users.
--   2. pgPolicy / enableRLS support in drizzle-orm requires the arm that is
--      still experimental; hand-writing avoids version-skew issues.
--   3. Storage bucket provisioning is pure SQL against storage.buckets.
--
-- All CREATE POLICY statements are preceded by DROP POLICY IF EXISTS so this
-- migration is safely re-runnable without "policy already exists" errors.
--
-- NOTE — storage.objects policies: every storage access is server-side via the
-- service role (which bypasses RLS entirely) against a private bucket.  No
-- storage.objects policies are needed for security and none are created here.
-- Attempting ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY on hosted
-- Supabase will fail with "must be owner of table objects".
--
-- Storage path convention (Phase 4): objects are stored as
--   "{letter_id}/{filename}"
-- pathed under the owning letter (SPEC §"Letter content").  Access is
-- exclusively server-side: the service role uploads objects, and the server
-- mints time-limited signed URLs for reads after a valid unlock or
-- saved-letter view.  No client-facing storage policy is needed or added.
-- =============================================================================


-- ---------------------------------------------------------------------------
-- 1. Foreign key: profiles.id → auth.users(id) ON DELETE CASCADE
--    Supabase's auth.users already exists; we just add the FK constraint.
--    This must live in a hand-written migration because drizzle-kit would
--    attempt to CREATE auth.users if we declared it in the ORM schema.
-- ---------------------------------------------------------------------------
ALTER TABLE "public"."profiles"
  ADD CONSTRAINT "profiles_id_auth_users_id_fk"
  FOREIGN KEY ("id")
  REFERENCES "auth"."users"("id")
  ON DELETE CASCADE;


-- ---------------------------------------------------------------------------
-- 2. Enable Row Level Security on all three app tables
-- ---------------------------------------------------------------------------
ALTER TABLE "public"."profiles"      ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."letters"       ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."letter_images" ENABLE ROW LEVEL SECURITY;


-- ---------------------------------------------------------------------------
-- 3. RLS policies — profiles
--    A user can SELECT / INSERT / UPDATE only their own row.
--    DELETE is left ungranted (account deletion is server-side / admin only).
-- ---------------------------------------------------------------------------

-- Own-row SELECT
DROP POLICY IF EXISTS "profiles: select own row" ON "public"."profiles";
CREATE POLICY "profiles: select own row"
  ON "public"."profiles"
  FOR SELECT
  USING (id = auth.uid());

-- Own-row INSERT (the id must match the caller's uid)
DROP POLICY IF EXISTS "profiles: insert own row" ON "public"."profiles";
CREATE POLICY "profiles: insert own row"
  ON "public"."profiles"
  FOR INSERT
  WITH CHECK (id = auth.uid());

-- Own-row UPDATE
DROP POLICY IF EXISTS "profiles: update own row" ON "public"."profiles";
CREATE POLICY "profiles: update own row"
  ON "public"."profiles"
  FOR UPDATE
  USING (id = auth.uid())
  WITH CHECK (id = auth.uid());


-- ---------------------------------------------------------------------------
-- 4. RLS policies — letters
--
--   INSERT: sender_id must equal the authenticated caller.
--   SELECT: only the user who saved the letter may read it (Received mail).
--           No general sender read-back — opening a letter is fire-and-forget.
--
--   The locked page, verify route, and grace-window reads all use the
--   service role via Drizzle (server-only), which bypasses RLS entirely.
--   Therefore we do NOT add an anon/unauthenticated SELECT policy that
--   would expose body / answer_normalized / claim_token.
--   No client UPDATE or DELETE policy is granted.
-- ---------------------------------------------------------------------------

-- Senders may INSERT their own letters
DROP POLICY IF EXISTS "letters: insert as sender" ON "public"."letters";
CREATE POLICY "letters: insert as sender"
  ON "public"."letters"
  FOR INSERT
  WITH CHECK (sender_id = auth.uid());

-- Saved-letter owners may SELECT (Received mail)
DROP POLICY IF EXISTS "letters: select saved by me" ON "public"."letters";
CREATE POLICY "letters: select saved by me"
  ON "public"."letters"
  FOR SELECT
  USING (saved_by = auth.uid());


-- ---------------------------------------------------------------------------
-- 5. RLS policies — letter_images
--    No permissive client policy.  All image access is mediated by the
--    service role: the server mints time-limited signed URLs after a valid
--    unlock or saved-letter view.  Enabling RLS with no permissive policy
--    means every direct client query returns 0 rows (default-deny).
-- ---------------------------------------------------------------------------
-- (No CREATE POLICY statements intentionally — RLS is enabled in section 2
--  with no permissive client policy, so default-deny applies to all clients.)


-- ---------------------------------------------------------------------------
-- 6. Storage: private "letters" bucket
--    Idempotent via ON CONFLICT DO NOTHING.
--    public = false → all object access requires service-role signed URLs.
--
--    We do NOT ALTER storage.objects or create storage.objects policies:
--    hosted Supabase does not grant ownership of that table to project roles,
--    and the service role bypasses RLS anyway so no policy is needed.
-- ---------------------------------------------------------------------------
INSERT INTO "storage"."buckets" (id, name, public)
VALUES ('letters', 'letters', false)
ON CONFLICT (id) DO NOTHING;
